In [1]:
import joblib
import json
from pathlib import Path

import pandas as pd

In [2]:
MODEL_DIR = Path("../models")

model = joblib.load(MODEL_DIR / "xgboost_model.pkl")

with open(MODEL_DIR / "synthetic_model_config.json") as f:
    config = json.load(f)

threshold = config["threshold"]
features = config["columns"]

## Load the dataset

In [3]:
train1 = pd.read_csv("../data/AIClusterKPI/train1.csv")
train1.head()

,timestamp,cpu-N1,cpu-N2,cpu-N3,cpu-N4,cpu-N6,cpu-N7,cpu-N8,mem_gb-N1,mem_gb-N2,...,net_in-N1,net_in-N2,net_in-N3,net_in-N4,net_in-N6,net_in-N7,net_in-N8,cluster_pending_cluster,cluster_api_latency_cluster,cluster_restarts_cluster
0,2026-03-31 10:00:00,6.680208,6.388542,5.020833,1.705208,7.151667,2.798333,10.565000,225.637970,195.436626,...,1.753424e+06,1.898670e+06,7.011507e+07,2.683055e+06,2.052080e+06,225615.200000,1.826642e+06,32.0,60.0,1.000000
1,2026-03-31 10:01:00,7.869792,6.191667,4.919792,2.240625,7.333333,2.113333,10.276667,225.636430,195.417273,...,2.333240e+06,1.991825e+06,7.143399e+07,2.727277e+06,2.090174e+06,242094.514286,1.812841e+06,32.0,60.0,1.285714
2,2026-03-31 10:02:00,7.313542,7.139583,4.612500,2.737500,7.091667,2.056667,10.683333,225.618736,195.417915,...,2.282198e+06,1.883804e+06,7.133766e+07,2.675908e+06,2.028816e+06,233625.923810,1.815652e+06,32.0,60.0,3.000000
3,2026-03-31 10:03:00,7.061458,6.390625,4.663542,2.367708,7.185000,2.058333,10.951667,225.622343,195.408842,...,2.008944e+06,1.863688e+06,7.510595e+07,3.013435e+06,2.389490e+06,197532.638095,1.790735e+06,32.0,60.0,3.142857
4,2026-03-31 10:04:00,7.319792,6.336458,4.673958,2.503125,7.753333,1.580000,10.360000,225.628160,195.410172,...,2.393010e+06,1.967841e+06,7.718859e+07,2.885227e+06,2.228725e+06,222493.019048,1.791938e+06,32.0,60.0,4.285714

In [4]:
train2 = pd.read_csv("../data/AIClusterKPI/train2.csv")
train2.head()

,timestamp,cpu-N1,cpu-N2,cpu-N3,cpu-N4,cpu-N6,cpu-N7,cpu-N8,mem_gb-N1,mem_gb-N2,...,net_in-N1,net_in-N2,net_in-N3,net_in-N4,net_in-N6,net_in-N7,net_in-N8,cluster_pending_cluster,cluster_api_latency_cluster,cluster_restarts_cluster
0,2026-04-08 22:00:00,9.760417,4.421875,5.272917,1.994792,18.351667,2.243333,9.965000,223.073399,195.785358,...,4.131676,2.881709,77.207812,2.476900,9.944299,0.347406,3.293577,37.0,60.0,17.0
1,2026-04-08 22:01:00,6.787500,4.960417,5.321875,1.130208,19.958333,2.256667,9.360000,223.055363,195.809792,...,4.381149,2.832858,80.016828,2.832742,10.757282,0.353732,3.285016,37.0,60.0,15.0
2,2026-04-08 22:02:00,7.842708,5.127083,5.969792,2.232292,22.720000,2.298333,10.563333,223.066864,195.788757,...,4.601410,2.966540,69.829389,2.084610,10.107977,0.402745,3.348294,37.0,60.0,15.0
3,2026-04-08 22:03:00,9.644792,4.425000,5.211458,1.757292,18.505000,2.260000,10.593333,223.049252,195.801384,...,4.103449,2.964366,72.016745,2.283314,10.226605,0.355678,3.268561,37.0,60.0,16.0
4,2026-04-08 22:04:00,7.397917,5.111458,4.821875,2.297917,28.073333,3.010000,10.928333,223.061558,195.773861,...,5.057377,2.884074,74.676581,3.036440,10.313928,0.344475,3.249787,37.0,60.0,17.0

In [5]:
test = pd.read_csv("../data/AIClusterKPI/test.csv")
test.head()

,timestamp,cpu-N1,cpu-N2,cpu-N3,cpu-N4,cpu-N6,cpu-N7,cpu-N8,mem_gb-N1,mem_gb-N2,...,net_in-N3,net_in-N4,net_in-N6,net_in-N7,net_in-N8,cluster_pending_cluster,cluster_api_latency_cluster,cluster_restarts_cluster,label,event_id
0,2026-04-26 23:06:00,6.770833,4.157292,5.280208,2.267708,6.491667,2.320000,9.091667,226.238632,195.225121,...,72.566780,2.803814,2.316449,0.107875,0.810465,37.0,60.0,17.0,0,normal
1,2026-04-26 23:07:00,4.647917,3.819792,4.568750,2.719792,7.795000,2.118333,9.955000,226.213146,195.195488,...,71.562196,2.365296,1.838819,0.096578,0.827169,37.0,60.0,16.0,0,Metric_Scraping
2,2026-04-26 23:08:00,4.728125,4.348958,4.335417,2.110417,8.186667,2.206667,7.855000,226.221027,195.155724,...,67.674734,2.726050,2.013627,0.160343,0.888129,37.0,60.0,17.0,0,Metric_Scraping
3,2026-04-26 23:09:00,6.239583,4.607292,4.751042,2.167708,7.190000,2.105000,9.511667,226.222054,195.165466,...,76.236175,2.489302,2.418586,0.108085,0.839065,37.0,60.0,17.0,0,Metric_Scraping
4,2026-04-26 23:10:00,4.892708,3.435417,4.666667,2.221875,7.083333,2.178333,9.418333,226.197456,195.163601,...,75.748608,2.690325,1.723902,0.119766,0.824586,37.0,60.0,15.0,0,Metric_Scraping

In [6]:
groundtruth = pd.read_csv("../data/AIClusterKPI/groundtruth.csv")
groundtruth.head()

,start_time,end_time,node,event,is_anomaly
0,2026-04-26 23:06:22.630569,2026-04-26 23:19:17.630569,N2,Metric_Scraping,0
1,2026-04-26 23:14:24.592023,2026-04-26 23:20:22.592023,N6,CPU_Sync_Stutter,1
2,2026-04-26 23:26:28.314219,2026-04-26 23:36:02.314219,N8,Network_Latency_Jitter,1
3,2026-04-26 23:33:29.519800,2026-04-26 23:42:15.519800,N7,Metric_Scraping,0
4,2026-04-26 23:35:30.738204,2026-04-26 23:43:53.738204,N3,Log_Rotation,0

### Check for missing values

In [7]:
datasets = {
    "train1": train1,
    "train2": train2,
    "test": test,
    "groundtruth": groundtruth,
}

for name, df in datasets.items():
    print(f"\n--- {name} ---")
    print("Columns:", df.columns.tolist())
    print(df.head(3).to_string(index=False))
    print("\nMissing values:", df.isna().sum().sum())

--- train1 ---
Columns: ['timestamp', 'cpu-N1', 'cpu-N2', 'cpu-N3', 'cpu-N4', 'cpu-N6', 'cpu-N7', 'cpu-N8', 'mem_gb-N1', 'mem_gb-N2', 'mem_gb-N3', 'mem_gb-N4', 'mem_gb-N6', 'mem_gb-N7', 'mem_gb-N8', 'disk_io-N1', 'disk_io-N2', 'disk_io-N3', 'disk_io-N4', 'disk_io-N6', 'disk_io-N7', 'disk_io-N8', 'net_in-N1', 'net_in-N2', 'net_in-N3', 'net_in-N4', 'net_in-N6', 'net_in-N7', 'net_in-N8', 'cluster_pending_cluster', 'cluster_api_latency_cluster', 'cluster_restarts_cluster']
          timestamp   cpu-N1   cpu-N2   cpu-N3   cpu-N4   cpu-N6   cpu-N7    cpu-N8  mem_gb-N1  mem_gb-N2  mem_gb-N3  mem_gb-N4  mem_gb-N6  mem_gb-N7  mem_gb-N8  disk_io-N1  disk_io-N2  disk_io-N3  disk_io-N4  disk_io-N6  disk_io-N7  disk_io-N8    net_in-N1    net_in-N2    net_in-N3    net_in-N4    net_in-N6     net_in-N7    net_in-N8  cluster_pending_cluster  cluster_api_latency_cluster  cluster_restarts_cluster
2026-03-31 10:00:00 6.680208 6.388542 5.020833 1.705208 7.151667 2.798333 10.565000 225.637970 195.436626 200.422260 221.739262 188.232273 243.924110 178.359390    0.042133    0.284000    0.405600    0.401600    0.006933    0.005867    0.011733 1.753424e+06 1.898670e+06 7.011507e+07 2.683055e+06 2.052080e+06 225615.200000 1.826642e+06                     32.0                         60.0                  1.000000
2026-03-31 10:01:00 7.869792 6.191667 4.919792 2.240625 7.333333 2.113333 10.276667 225.636430 195.417273 200.468998 221.716573 188.233941 243.924101 178.374611    0.043276    0.290667    0.401600    0.396076    0.006933    0.004343    0.010971 2.333240e+06 1.991825e+06 7.143399e+07 2.727277e+06 2.090174e+06 242094.514286 1.812841e+06                     32.0                         60.0                  1.285714
2026-03-31 10:02:00 7.313542 7.139583 4.612500 2.737500 7.091667 2.056667 10.683333 225.618736 195.417915 200.470647 221.713154 188.235929 243.926721 178.387464    0.042781    0.274857    0.366095    0.369676    0.006552    0.004876    0.012190 2.282198e+06 1.883804e+06 7.133766e+07 2.675908e+06 2.028816e+06 233625.923810 1.815652e+06                     32.0                         60.0                  3.000000

Missing values: 0

--- train2 ---
Columns: ['timestamp', 'cpu-N1', 'cpu-N2', 'cpu-N3', 'cpu-N4', 'cpu-N6', 'cpu-N7', 'cpu-N8', 'mem_gb-N1', 'mem_gb-N2', 'mem_gb-N3', 'mem_gb-N4', 'mem_gb-N6', 'mem_gb-N7', 'mem_gb-N8', 'disk_io-N1', 'disk_io-N2', 'disk_io-N3', 'disk_io-N4', 'disk_io-N6', 'disk_io-N7', 'disk_io-N8', 'net_in-N1', 'net_in-N2', 'net_in-N3', 'net_in-N4', 'net_in-N6', 'net_in-N7', 'net_in-N8', 'cluster_pending_cluster', 'cluster_api_latency_cluster', 'cluster_restarts_cluster']
          timestamp   cpu-N1   cpu-N2   cpu-N3   cpu-N4    cpu-N6   cpu-N7    cpu-N8  mem_gb-N1  mem_gb-N2  mem_gb-N3  mem_gb-N4  mem_gb-N6  mem_gb-N7  mem_gb-N8  disk_io-N1  disk_io-N2  disk_io-N3  disk_io-N4  disk_io-N6  disk_io-N7  disk_io-N8  net_in-N1  net_in-N2  net_in-N3  net_in-N4  net_in-N6  net_in-N7  net_in-N8  cluster_pending_cluster  cluster_api_latency_cluster  cluster_restarts_cluster
2026-04-08 22:00:00 9.760417 4.421875 5.272917 1.994792 18.351667 2.243333  9.965000 223.073399 195.785358 199.314373 221.734863 188.168655 243.866482 179.253559    0.067733    0.306133    0.345067    0.372000    0.005867    0.004800    0.012267   4.131676   2.881709  77.207812   2.476900   9.944299   0.347406   3.293577                     37.0                         60.0                      17.0
2026-04-08 22:01:00 6.787500 4.960417 5.321875 1.130208 19.958333 2.256667  9.360000 223.055363 195.809792 199.297684 221.751545 188.167717 243.865555 179.256561    0.052000    0.281600    0.361067    0.321600    0.005867    0.004267    0.011200   4.381149   2.832858  80.016828   2.832742  10.757282   0.353732   3.285016                     37.0                         60.0                      15.0
2026-04-08 22:02:00 7.842708 5.127083 5.969792 2.232292 22.720000 2.298333 10.563333 223.066864 195.788757 199.303989 221.835205 188.173721 243.874287 179.275486    0.051467    0.301867    0.316267    0.362133    0.005867    0.005333    0.013333   4.601410   2.966540  69.829389   2.084610  10.107977   0.402745   3.348294                     37.0                         60.0                      15.0

Missing values: 0

--- test ---
Columns: ['timestamp', 'cpu-N1', 'cpu-N2', 'cpu-N3', 'cpu-N4', 'cpu-N6', 'cpu-N7', 'cpu-N8', 'mem_gb-N1', 'mem_gb-N2', 'mem_gb-N3', 'mem_gb-N4', 'mem_gb-N6', 'mem_gb-N7', 'mem_gb-N8', 'disk_io-N1', 'disk_io-N2', 'disk_io-N3', 'disk_io-N4', 'disk_io-N6', 'disk_io-N7', 'disk_io-N8', 'net_in-N1', 'net_in-N2', 'net_in-N3', 'net_in-N4', 'net_in-N6', 'net_in-N7', 'net_in-N8', 'cluster_pending_cluster', 'cluster_api_latency_cluster', 'cluster_restarts_cluster', 'label', 'event_id']
          timestamp   cpu-N1   cpu-N2   cpu-N3   cpu-N4   cpu-N6   cpu-N7   cpu-N8  mem_gb-N1  mem_gb-N2  mem_gb-N3  mem_gb-N4  mem_gb-N6  mem_gb-N7  mem_gb-N8  disk_io-N1  disk_io-N2  disk_io-N3  disk_io-N4  disk_io-N6  disk_io-N7  disk_io-N8  net_in-N1  net_in-N2  net_in-N3  net_in-N4  net_in-N6  net_in-N7  net_in-N8  cluster_pending_cluster  cluster_api_latency_cluster  cluster_restarts_cluster  label        event_id
2026-04-26 23:06:00 6.770833 4.157292 5.280208 2.267708 6.491667 2.320000 9.091667 226.238632 195.225121 195.980602 221.186451 191.692078 243.864666 179.303890    0.071200    0.301067    0.389600    0.349067    0.005333    0.005600    0.008533   3.149695   1.086231  72.566780   2.803814   2.316449   0.107875   0.810465                     37.0                         60.0                      17.0      0          normal
2026-04-26 23:07:00 4.647917 3.819792 4.568750 2.719792 7.795000 2.118333 9.955000 226.213146 195.195488 195.980583 221.176403 191.695404 243.864952 179.310421    0.068533    0.301067    0.345067    0.373333    0.006933    0.003200    0.009600   3.884522   1.421796  71.562196   2.365296   1.838819   0.096578   0.827169                     37.0                         60.0                      16.0      0 Metric_Scraping
2026-04-26 23:08:00 4.728125 4.348958 4.335417 2.110417 8.186667 2.206667 7.855000 226.221027 195.155724 195.961243 221.175076 191.694244 243.868584 179.312431    0.064000    0.275200    0.331467    0.364800    0.005333    0.005867    0.011733   3.375061   1.074745  67.674734   2.726050   2.013627   0.160343   0.888129                     37.0                         60.0                      17.0      0 Metric_Scraping

Missing values: 0

--- groundtruth ---
Columns: ['start_time', 'end_time', 'node', 'event', 'is_anomaly']
                start_time                   end_time node                  event  is_anomaly
2026-04-26 23:06:22.630569 2026-04-26 23:19:17.630569   N2        Metric_Scraping           0
2026-04-26 23:14:24.592023 2026-04-26 23:20:22.592023   N6       CPU_Sync_Stutter           1
2026-04-26 23:26:28.314219 2026-04-26 23:36:02.314219   N8 Network_Latency_Jitter           1

Missing values: 0

### Types

Timestamp is a `str`, convert into dateTime data type

In [13]:
for name, df in datasets.items():
    print(f"\n--- {name} ---")
    print("Types:\n", df.dtypes)
    print("Describe:\n", df.describe())

--- train1 ---
Types:
 timestamp                          str
cpu-N1                         float64
cpu-N2                         float64
cpu-N3                         float64
cpu-N4                         float64
cpu-N6                         float64
cpu-N7                         float64
cpu-N8                         float64
mem_gb-N1                      float64
mem_gb-N2                      float64
mem_gb-N3                      float64
mem_gb-N4                      float64
mem_gb-N6                      float64
mem_gb-N7                      float64
mem_gb-N8                      float64
disk_io-N1                     float64
disk_io-N2                     float64
disk_io-N3                     float64
disk_io-N4                     float64
disk_io-N6                     float64
disk_io-N7                     float64
disk_io-N8                     float64
net_in-N1                      float64
net_in-N2                      float64
net_in-N3                      float64
net_in-N4                      float64
net_in-N6                      float64
net_in-N7                      float64
net_in-N8                      float64
cluster_pending_cluster        float64
cluster_api_latency_cluster    float64
cluster_restarts_cluster       float64
dtype: object
Describe:
              cpu-N1        cpu-N2        cpu-N3        cpu-N4        cpu-N6  \
count  11089.000000  11089.000000  11089.000000  11089.000000  11089.000000
mean       7.682807      6.371489      4.922428      2.510070      8.640903
std        1.044359      1.460162      0.946781      2.402561      3.566863
min        1.158333     -7.426042    -22.686682    -10.461458     -3.516667
25%        7.033333      5.497917      4.661458      2.054167      7.248333
50%        7.582292      6.405208      4.858333      2.254167      7.516667
75%        8.243750      7.178125      5.170833      2.563542      7.913333
max       16.423958     20.652083     16.432292     74.516667     30.751667

             cpu-N7        cpu-N8     mem_gb-N1     mem_gb-N2     mem_gb-N3  \
count  11089.000000  11089.000000  11089.000000  11089.000000  11089.000000
mean       2.088559      9.979551    224.070561    195.798134    200.255114
std        0.744925      1.009466      0.963746      0.373500      0.194107
min       -9.380000     -1.988333    221.924933    194.825377    199.569411
25%        1.976667      9.511667    223.447237    195.442170    200.124888
50%        2.060000      9.761667    223.514654    195.910255    200.244856
75%        2.176667     10.388333    225.574450    196.077082    200.377921
max       14.368333     22.900000    225.779080    196.538916    200.815104

       ...     net_in-N1     net_in-N2     net_in-N3     net_in-N4  \
count  ...  1.108900e+04  1.108900e+04  1.108900e+04  1.108900e+04
mean   ...  1.667848e+05  1.495239e+05  5.559903e+06  2.497656e+05
std    ...  6.224027e+05  6.213828e+05  1.996817e+07  1.525005e+06
min    ...  1.563578e+00  8.319582e-01  1.758037e+00  2.056129e+00
25%    ...  2.528954e+00  1.124051e+00  7.045890e+01  2.507422e+00
50%    ...  3.148931e+00  1.279301e+00  7.276167e+01  2.630419e+00
75%    ...  3.495630e+00  1.881337e+00  7.522029e+01  2.785763e+00
max    ...  1.441086e+07  2.214731e+07  9.472599e+07  9.682669e+07

          net_in-N6      net_in-N7     net_in-N8  cluster_pending_cluster  \
count  1.108900e+04   11089.000000  1.108900e+04             11089.000000
mean   1.611478e+05   13388.884590  1.500995e+05                32.002860
std    5.699145e+05   48732.522696  5.801188e+05                 0.070515
min    1.395575e+00       0.078075  6.021500e-01                32.000000
25%    1.947983e+00       0.114456  9.141617e-01                32.000000
50%    2.065318e+00       0.137717  1.153857e+00                32.000000
75%    2.229330e+00       0.207919  2.119173e+00                32.000000
max    5.072100e+06  369221.295238  1.308788e+07                36.000000

       cluster_api_latency_cluster  cluster_restarts_cluster
count                      11089.0              11089.000000
mean                          60.0                 16.567435
std                            0.0                  3.443898
min                           60.0                  1.000000
25%                           60.0                 15.285714
50%                           60.0                 16.000000
75%                           60.0                 17.000000
max                           60.0                 52.285714

[8 rows x 31 columns]

--- train2 ---
Types:
 timestamp                          str
cpu-N1                         float64
cpu-N2                         float64
cpu-N3                         float64
cpu-N4                         float64
cpu-N6                         float64
cpu-N7                         float64
cpu-N8                         float64
mem_gb-N1                      float64
mem_gb-N2                      float64
mem_gb-N3                      float64
mem_gb-N4                      float64
mem_gb-N6                      float64
mem_gb-N7                      float64
mem_gb-N8                      float64
disk_io-N1                     float64
disk_io-N2                     float64
disk_io-N3                     float64
disk_io-N4                     float64
disk_io-N6                     float64
disk_io-N7                     float64
disk_io-N8                     float64
net_in-N1                      float64
net_in-N2                      float64
net_in-N3                      float64
net_in-N4                      float64
net_in-N6                      float64
net_in-N7                      float64
net_in-N8                      float64
cluster_pending_cluster        float64
cluster_api_latency_cluster    float64
cluster_restarts_cluster       float64
dtype: object
Describe:
             cpu-N1       cpu-N2       cpu-N3       cpu-N4       cpu-N6  \
count  6482.000000  6482.000000  6482.000000  6482.000000  6482.000000
mean      8.701793     7.027653     5.192103     2.450467    15.220173
std       1.249643     2.157216     0.732947     2.010149     5.294157
min      -1.012500    -5.643750    -4.260417    -8.332292     5.041667
25%       7.965885     4.950000     4.897135     2.048958    11.447976
50%       8.667708     7.908854     5.128125     2.233185    14.486667
75%       9.369792     8.786458     5.435417     2.491890    18.431667
max      34.096485    18.620982    17.285714    64.946577    38.029952

            cpu-N7       cpu-N8    mem_gb-N1    mem_gb-N2    mem_gb-N3  ...  \
count  6482.000000  6482.000000  6482.000000  6482.000000  6482.000000  ...
mean      2.078945    10.279101   223.014859   195.578387   196.824179  ...
std       0.728911     1.287851     0.075436     0.137630     1.097029  ...
min     -12.301667    -0.533333   220.192285   195.181183   195.559563  ...
25%       1.938690     9.533869   222.998066   195.489946   196.105443  ...
50%       2.043333    10.181667   223.016159   195.578810   196.334654  ...
75%       2.181667    10.893036   223.042345   195.672854   196.629966  ...
max      14.556667    20.911667   223.333199   195.981842   199.493496  ...

         net_in-N1    net_in-N2    net_in-N3    net_in-N4    net_in-N6  \
count  6482.000000  6482.000000  6482.000000  6482.000000  6482.000000
mean      4.521735     2.090547    70.946452     2.884726     5.898074
std      14.752831     1.943417    16.180752     2.606282     7.670388
min       2.039502     0.803212     1.689664     1.763080     1.150057
25%       3.027540     1.488074    70.116825     2.448945     3.800942
50%       3.523381     1.714486    72.648623     2.616395     5.186119
75%       4.124320     2.441971    75.137570     2.800841     7.114458
max     453.154657    70.577321   625.952439   109.213327   314.004446

         net_in-N7    net_in-N8  cluster_pending_cluster  \
count  6482.000000  6482.000000              6482.000000
mean      0.783272     2.189853                37.001322
std      10.113525     7.259118                 0.035288
min       0.076148     0.642199                37.000000
25%       0.126160     1.271252                37.000000
50%       0.148696     1.564624                37.000000
75%       0.182419     2.449745                37.000000
max     403.696600   322.121055                38.142857

       cluster_api_latency_cluster  cluster_restarts_cluster
count                       6482.0               6482.000000
mean                          60.0                 16.146053
std                            0.0                  1.322883
min                           60.0                 12.000000
25%                           60.0                 15.285714
50%                           60.0                 16.000000
75%                           60.0                 17.000000
max                           60.0                 35.000000

[8 rows x 31 columns]

--- test ---
Types:
 timestamp                          str
cpu-N1                         float64
cpu-N2                         float64
cpu-N3                         float64
cpu-N4                         float64
cpu-N6                         float64
cpu-N7                         float64
cpu-N8                         float64
mem_gb-N1                      float64
mem_gb-N2                      float64
mem_gb-N3                      float64
mem_gb-N4                      float64
mem_gb-N6                      float64
mem_gb-N7                      float64
mem_gb-N8                      float64
disk_io-N1                     float64
disk_io-N2                     float64
disk_io-N3                     float64
disk_io-N4                     float64
disk_io-N6                     float64
disk_io-N7                     float64
disk_io-N8                     float64
net_in-N1                      float64
net_in-N2                      float64
net_in-N3                      float64
net_in-N4                      float64
net_in-N6                      float64
net_in-N7                      float64
net_in-N8                      float64
cluster_pending_cluster        float64
cluster_api_latency_cluster    float64
cluster_restarts_cluster       float64
label                            int64
event_id                           str
dtype: object
Describe:
             cpu-N1       cpu-N2       cpu-N3       cpu-N4       cpu-N6  \
count  3029.000000  3029.000000  3029.000000  3029.000000  3029.000000
mean      5.576546     4.401835     5.007221     2.431594     7.496627
std       1.331852    12.503086     1.249900     2.863216     1.583817
min      -2.005208  -674.641667   -26.502524  -113.956250    -2.225000
25%       4.743750     4.157292     4.694792     2.067708     6.866667
50%       5.119792     4.428125     4.920833     2.268750     7.395000
75%       6.512500     4.763542     5.250000     2.571875     7.940000
max      24.889412    98.757185    17.621875    60.905208    27.685000

            cpu-N7       cpu-N8    mem_gb-N1    mem_gb-N2    mem_gb-N3  ...  \
count  3029.000000  3029.000000  3029.000000  3029.000000  3029.000000  ...
mean      2.055440     9.908338   226.238986   195.081034   196.793790  ...
std       3.083770     1.752333     0.072302     0.196374     0.459993  ...
min    -155.575000    -8.679707   224.961689   193.752102   195.281143  ...
25%       2.028333     9.033333   226.220745   194.989571   196.529217  ...
50%       2.111667     9.658333   226.239044   195.081779   196.822411  ...
75%       2.205000    10.463333   226.261143   195.172062   196.999664  ...
max      13.480000    42.673333   226.565804   196.293507   199.606472  ...

         net_in-N2    net_in-N3    net_in-N4    net_in-N6    net_in-N7  \
count  3029.000000  3029.000000  3029.000000  3029.000000  3029.000000
mean      1.420747    70.446141     2.924143     2.125074     0.187775
std       1.535041    12.478819     3.598941     0.753865     0.384936
min       0.021100     2.560387     0.121735     0.270310     0.071328
25%       1.108104    69.768395     2.442110     1.843010     0.129193
50%       1.175506    72.637092     2.635121     2.050457     0.155576
75%       1.284306    75.549691     2.853065     2.255919     0.182208
max      31.175173   105.159856   177.435666    16.220031    11.104943

         net_in-N8  cluster_pending_cluster  cluster_api_latency_cluster  \
count  3029.000000              3029.000000                       3029.0
mean      1.957279                37.002971                         60.0
std       3.347336                 0.054437                          0.0
min       0.155108                37.000000                         60.0
25%       0.862943                37.000000                         60.0
50%       0.901906                37.000000                         60.0
75%       0.961692                37.000000                         60.0
max      47.509990                38.000000                         60.0

       cluster_restarts_cluster        label
count               3029.000000  3029.000000
mean                  17.570485     0.368769
std                    6.103473     0.482551
min                   12.000000     0.000000
25%                   16.000000     0.000000
50%                   16.000000     0.000000
75%                   17.000000     1.000000
max                   65.000000     1.000000

[8 rows x 32 columns]

--- groundtruth ---
Types:
 start_time      str
end_time        str
node            str
event           str
is_anomaly    int64
dtype: object
Describe:
        is_anomaly
count  598.000000
mean     0.242475
std      0.428939
min      0.000000
25%      0.000000
50%      0.000000
75%      0.000000
max      1.000000

In [21]:
train1["timestamp"] = pd.to_datetime(train1["timestamp"])
print(train1["timestamp"].dtypes)
print(train1["timestamp"].isna().sum())

train2["timestamp"] = pd.to_datetime(train2["timestamp"])
print(train2["timestamp"].dtypes)
print(train2["timestamp"].isna().sum())

datetime64[us]
0
datetime64[us]
0

In [24]:
groundtruth["start_time"], groundtruth["end_time"] = pd.to_datetime(groundtruth["start_time"]), pd.to_datetime(groundtruth["end_time"])

print(groundtruth["start_time"].dtypes)
print(groundtruth["start_time"].isna().sum())

print(groundtruth["end_time"].dtypes)
print(groundtruth["end_time"].isna().sum())

datetime64[us]
0
datetime64[us]
0

### Timestamp integrity

In [31]:
is_chronological = train1["timestamp"].is_monotonic_increasing
print(is_chronological)

intervals = train1["timestamp"].diff()
print(intervals.value_counts())

duplicated = train1["timestamp"].duplicated()
print(duplicated.sum())

True
timestamp
0 days 00:01:00    11088
Name: count, dtype: int64
0

In [33]:
is_chronological = train2["timestamp"].is_monotonic_increasing
print(is_chronological)

intervals = train2["timestamp"].diff()
print(intervals.value_counts())

duplicated = train2["timestamp"].duplicated()
print(duplicated.sum())

True
timestamp
0 days 00:01:00    6481
Name: count, dtype: int64
0

### Check for unusual or invalid values
The dataset documentation mentions that negative CPU readings can arise from counter-reset or differential artefacts. This is around 2.4% of the dataset has negative CPU values

In [39]:
has_negative = (train1.select_dtypes(include=['number','int','float']) < 0).sum()
print(has_negative)

cpu-N1                          0
cpu-N2                         13
cpu-N3                         46
cpu-N4                         39
cpu-N6                          6
cpu-N7                         48
cpu-N8                          3
mem_gb-N1                       0
mem_gb-N2                       0
mem_gb-N3                       0
mem_gb-N4                       0
mem_gb-N6                       0
mem_gb-N7                       0
mem_gb-N8                       0
disk_io-N1                      0
disk_io-N2                      0
disk_io-N3                      0
disk_io-N4                      0
disk_io-N6                      0
disk_io-N7                      0
disk_io-N8                      0
net_in-N1                       0
net_in-N2                       0
net_in-N3                       0
net_in-N4                       0
net_in-N6                       0
net_in-N7                       0
net_in-N8                       0
cluster_pending_cluster         0
cluster_api_latency_cluster     0
cluster_restarts_cluster        0
dtype: int64

In [40]:
has_negative = (train2.select_dtypes(include=['number','int','float']) < 0).sum()
print(has_negative)

cpu-N1                          1
cpu-N2                          9
cpu-N3                          7
cpu-N4                         21
cpu-N6                          0
cpu-N7                         23
cpu-N8                          1
mem_gb-N1                       0
mem_gb-N2                       0
mem_gb-N3                       0
mem_gb-N4                       0
mem_gb-N6                       0
mem_gb-N7                       0
mem_gb-N8                       0
disk_io-N1                      0
disk_io-N2                      0
disk_io-N3                      0
disk_io-N4                      0
disk_io-N6                      0
disk_io-N7                      0
disk_io-N8                      0
net_in-N1                       0
net_in-N2                       0
net_in-N3                       0
net_in-N4                       0
net_in-N6                       0
net_in-N7                       0
net_in-N8                       0
cluster_pending_cluster         0
cluster_api_latency_cluster     0
cluster_restarts_cluster        0
dtype: int64

### Class labels

In [45]:
# class balance
test["label"].value_counts()

label
0    1912
1    1117
Name: count, dtype: int64

In [46]:
test.groupby(["label", "event_id"]).size().sort_values(ascending=False)

label  event_id
0      Metric_Scraping           782
       Log_Rotation              690
       normal                    440
1      Metric_Scraping           269
       Network_Latency_Jitter    256
       Log_Rotation              239
       CPU_Sync_Stutter          198
       Memory_Leak_Gradual       155
dtype: int64

In [47]:
groundtruth.groupby(["event", "is_anomaly"]).size()

event                   is_anomaly
CPU_Sync_Stutter        1              51
Log_Rotation            0             204
Memory_Leak_Gradual     1              40
Metric_Scraping         0             249
Network_Latency_Jitter  1              54
dtype: int64